---
title: "Confidence_intervals"
author: "Guillem"
date: "5 de febrero de 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## INTERVALOS DE CONFIANZA


### Test de Student

```{r}
set.seed(1000)

muestra_iris <- sample(1:150, 30, replace = TRUE)

len_petal <- iris[muestra_iris,]$Petal.Length


conf_int <- t.test(len_petal, conf.level = 0.95)$conf.int

conf_int

#¿Qué papael juega la confianza en los intervalos de confianza?
  
set.seed(2020)
valores_población <- rnorm(10^7)

(mu<-mean(valores_población))

muestras <- replicate(200, sample(valores_población, 50, replace = TRUE))


ConfIntT <- function(X, confianza = 0.95) {
  t.test(X, conf.level = confianza)$conf.int
}


conf_int_t <- apply(muestras, FUN = ConfIntT, MARGIN = 2)

conf_int_t

conf_cont_mu <- length(which((mu>=conf_int_t[1,]) & (mu<= conf_int_t[2,])))

conf_cont_mu / 200 * 100

```
```{r, include=FALSE}
plot(1, type = "n", xlim=c(-0.8, 0.8), ylim=c(0,200), xlab = "Valores", ylab = "Repeticiones", main = "")
seg.int <- function(i) {
  color = "light blue";
  if ((mu< conf_int_t[1, i] | mu> conf_int_t[2, i])){color = "red"} 
  segments(conf_int_t[1,i], i, conf_int_t[2,i], col = color, lwd=2)
}
sapply(1:200, FUN = seg.int) 
abline(v=mu, lwd=2)
```

### Método exacto o de Clopper-Pearson
```{r}
library(epitools)

set.seed(1000)
n_flores <- sample(1:150, 60, replace=TRUE)

muestra_flores <- iris[n_flores,]

head(muestra_flores, 10)

count_flores <- table(muestra_flores$Species=="setosa")[2]

count_flores

# Calculamos el intervalo de confianza al 95% de confianza con la función binom.exact
binom.exact(count_flores,60, conf.level = 0.95)

```
### Método de Wilson

```{r}
binom.wilson(count_flores, 60, conf.level = 0.95)
```

### Fórmula de Laplace

```{r}
# Necesitamos que n>100 por lo que las flores no sirven. También necesitamos que np > 10 y n(1-p) > 10

muestraL <- sample(c(TRUE, FALSE), 500, replace = TRUE)

muestraL <- table(muestraL)[2]


muestraL

binom.approx(muestraL, 500, conf.level = 0.95)


# Aún así si lo utilizamos en la muestra iris, aunque no tendremos todas las condiciones cumplidas por lo que no es un estimador fiable

binom.approx(count_flores, 60, conf.level = 0.95)

```

### Intervalo de confianza para la varianza de una población normal

```{r}
tiempo = c(12, 13, 13, 14, 14, 14, 15, 15, 16, 17, 18, 18, 19, 19, 25, 25, 26, 27, 30, 33, 34, 35, 40, 40, 51, 51, 58, 59, 83)

n <- length(tiempo)
(var_muestra <- var(tiempo))

(cuantil_izquierda <- qchisq(1-0.05/2, n-1))

(cuantil_derecho <- qchisq(0.05/2, n-1))

valor_izquierdo <- (n-1)*var_muestra/cuantil_izquierda

valor_derecho <- (n-1)*var_muestra/cuantil_derecho

conf_int <- c(valor_izquierdo, valor_derecho)

conf_int

conf_int_sd <- c(sqrt(valor_izquierdo), sqrt(valor_derecho))

conf_int_sd
```
#### Intervalos de confianza con EnvStats

```{r}
library(EnvStats)

width_muestra <- iris[n_flores,]$Sepal.Width

hist(width_muestra)

varTest(width_muestra, conf.level = 0.95)$conf.int

sqrt(varTest(width_muestra, conf.level = 0.95)$conf.int)

```
### Método Bootstrap

```{r}
# En el caso de este ejercicio no podemos usar la fucnción anterior al no poder considerar que se distribuye como una normal, por lo que hacemos bootsrap

set.seed(42)
X <- replicate(1000, var(sample(iris[n_flores, ]$Petal.Length, replace = TRUE)))

alpha = 0.05

boots_interval <- c(quantile(X, alpha/2),
                    quantile(X, 1- alpha/2))
round(boots_interval, 3)

# También podemos utilizar la función boot del paquete boot

library(boot)

var_boot <- function(X, indices) {var(X[indices])}


simulacion <- boot(iris[n_flores,]$Petal.Length, var_boot, 1000)

boot.ci(simulacion) # Para sacar el intervalo de confianza de la simulacion

boot.ci(simulacion)$percent[4:5]

?boot.ci
```

