---
title: "DistribucionesContinuas"
author: "Guillem"
date: "16 April 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# DISTRIBUCIÓN UNIFORME

Sea X una v.a. distribuida en una $U(-1, 1)$

```{r}
dunif(x = 0.5, min=-1, max = 1)

punif(q = 0.5, min = -1, max = 1)

runif(n = 5, min = -1, max = 1)
```

# EJEMPLO DE CUANTILES CON DADOS DE PARCHÍS

```{r}
ddado <- function(x, n=6){
  sapply(x, FUN = function(x){
    if (x %in% c(1:n)){return(1/n)}
    else {return(0)}}
  )
}

ddado(1:10, n = 6)

pdado <- function(x, n = 6){
  sapply(x, FUN = function(y) { if (y<1) { return(0)} else{if (y>=n){return(1)}else{return(sum(ddado(c(1:(floor(y))), n = n)))}}})}

pdado(0:11, 6)

qdado <- function(p, n = 6){
  sapply(p, FUN = function(pp=p, nn=n)
  {
    if(pp < 0 | pp >1) {return(NA)} 
    else {
    aux <- pp >= pdado(1:n, nn)
    aux
    ifelse(all(!aux), return(1), return(max(which(pp>=pdado(1:n, nn)))))}
  })
}

qdado(1.5)

qdado(c(0.1, 0.5, .6, .8, 1, 1.3, 1.5))
```

```{r}
a <- runif(10, 0, 1)
qdado(a)
```

# DISTRIBUCIÓN EXPONENCIAL

```{r}
dexp(0.001, rate = 3)

pexp(0.5, rate = 3)

rexp(10, rate = 3)
```

```{r}
lambda=10
par(mfrow=c(1,2))
curve(dexp(x,rate=lambda),xlim=c(-0.05,round(qexp(0.99,rate=lambda,2),2)+0.25),
      ylim=c(0,dexp(0,lambda)+0.1),col="blue",
      main=paste0("Función densidad Exp(",lambda,")"),
      ylab=paste0("dexp(x,rate=",lambda,")"))
curve(pexp(x,rate=lambda),xlim=c(-0.05,qexp(0.999,10)),ylim=c(0,1.1),col="blue",
      main=paste0("Función de distribución Exp(",lambda,")"),
      ylab=paste0("pexp(x,rate=",lambda,")"))
par(mfrow=c(1,1))
```

# DISTRIBUCIÓN NORMAL

```{r}
dnorm(2, mean = 1, sd = 2)

pnorm(2, mean = 1, sd = 2)

qnorm(0.95, mean = 1, sd = 2)

rnorm(n = 5, mean = 1, sd = 2)
```