---
title: "ParaTest"
author: "Guillem"
date: "6 de febrero de 2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Contraste de $\mu$ de normal con $\sigma$ desconocida con t.test

```{r}
# el parámetro alternative puede tomar tres valores: "two.sided" (por defecto, bilateral), "less" (mu < media), "greater" (mu > media)

set.seed(2020)
flores_ele <- sample(1:150, 40, replace = TRUE)

long_sep_mue <- iris[flores_ele,]$Sepal.Length

t.test(long_sep_mue, mu = 5.7, conf.level = 0.95, alternative = "greater")

test_t <- t.test(long_sep_mue, mu = 5.7, conf.level = 0.95, alternative = "greater")

test_t$conf.int

test_t$p.value
```

## Contrates de proporciones $p$ con binom.test

```{r}
binom.test(21, 25, p=0.8,alternative = "greater", conf.leve = 0.95)

library(MASS)

set.seed(1001)
madres_elegidas <- sample(1:189,40, replace = TRUE)
muestra_madres <- birthwt[madres_elegidas,]

x <- table(muestra_madres$smoke)[2]

binom.test(x,length(madres_elegidas), p=0.3, alternative = "greater")
```
Rechazaremos la $H_0$ ya que el $p-valor$ es menor a 0.05 que es el nivel de significación que hemos elegido
